### PR TITLE
Add rwxrob

### PR DESCRIPTION
**Pull request by NikolaRHristov**

### CODE REVIEW

**Comment by goproslowyo** [comment]
Rob doesn't hack or stream hacking content. Rob mostly talks. A lot of talking and a lot of opinions. Or fish screensavers. No hacking though.

**Comment by rwxrob** [comment]
I haven't had fish screensavers for more than six months, but hey, obviously you have interests and an agenda beyond actually helping people. Thanks for the clarity.

**Comment by crypto-dot** [comment]
Fish aquarium security is important.

**Comment by goproslowyo** [comment]
KEKW someone's upset about not being on a list. This is list is highly curated -- you're welcome to curate your own!

**Pull request closed without merging**
