### PR TITLE
Adding myself

### PR DESCRIPTION
**Pull request by goproslowyo**

### CODE REVIEW

**Review by 0xLGG — APPROVED** [review]
even though it is not the best behavior, adding yourself to a list like this, I will make for obvious reasons (being that you're awesome) make an exception to this.

**Comment by goproslowyo** [comment]
Chad very nicely added me to the list PR #3 but I need to merge the main branch to incorporate changes to the repo since that PR was created. #3 was closed and #4 was opened it it's place.

**Comment by s0ldier93** [comment]
Good to go

**Review by 0xLGG — APPROVED** [review]
let's try again

**Review by s0ldier93 — APPROVED** [review]
Good 3

**Review by 0xLGG — APPROVED** [review]
let's approve this already

**Pull request merged**
