### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by thejoker3000**
Add theprimeagen

### CODE REVIEW

**Comment by goproslowyo** [comment]
Is he really an infosec hacker tho? He seems more like a loud obnoxious hype-train kinda dude...

**Comment by thejoker3000** [comment]
Did you even read the title of where I added this person? Under **coders**

**Comment by goproslowyo** [comment]
Yup, read it loud and clear -- that's not a persuasive way to get someone to merge your PR by the way.

So he's an infosec coder? Don't think so ...I've seen his stream before he's obnoxious and toxic.

**Comment by thejoker3000** [comment]
Then you should remove some of the other streamers from the list. I've never seen, for example, cmgriffing do security coding or anything related. You just don't want to add someone "toxic" to the list.

**Comment by goproslowyo** [comment]
You make a very good point -- I will look into all those since the list was
made as a direct copy from an original list:
https://docs.google.com/document/d/e/2PACX-1vR_h7BQvuL0cTfTBPA3ATwv8JZP4_YBsudR_FYoEtcxMD9q0x3KrF_WiHHT6UhzdaXhFt-ZkJ1qHbKZ/pub

**Pull request closed without merging**
