### PR TITLE
Add a script to let user sort streamers

### PR DESCRIPTION
**Pull request by Douile**
This PR adds a script that allows users to click some of the table headings (online, streamer) and sort the list. I believe this makes the list easier to use as you can quickly sort online streamers to the top. The javascript is not that nice but it works :).

### CODE REVIEW

**Comment by Douile** [comment]
Live example here: https://douile.github.io/infosecstreams.github.io/

**Comment by goproslowyo** [comment]
@Douile this is awesome! I'm curious if we can add a default sort order of online streamers followed by the "hours streamed over two weeks" order? No biggie if not -- this is fantastic!

**Comment by Douile** [comment]
@goproslowyo like 3922571b22983cf070defb40841b4c4be0c89ad3 ?

**Comment by goproslowyo** [comment]
@Douile Almost...! Beggar can't be choosers so feel free to tell me no -- but here's two pictures:

So like in this image when you're sorted by online first, after the first two it's just kinda... random?

old

can it be sorted like? 
```
online 1
online 2
most-hours-streamed-1
most-hours-streamed-2
most-hours-streamed-3
etc..
```

**Comment by Douile** [comment]
@goproslowyo okay that should work, is that what you meant in your previous comment? should I revert defaulting to sorting by online?

**Comment by goproslowyo** [comment]
@Douile You are awesome, thank you much! 🥇🥳🦜

**Pull request merged**
